image: docker.siemens.com/code-ops/poetry-docker

stages:
  - check
  - deploy

format_and_style:
  stage: check
  script:
    - poetry install
    - black .
    - flake8 .
  except:
    - master

pages:
  stage: deploy
  script:
    - poetry install
    - poetry run sphinx-build docs/source docs/build
    - cp -r docs/build public
  only:
    - master
  artifacts:
    paths:
      - public
    expire_in: 1 day
