image: python:3.7-alpine

variables:
  PIP_INDEX: https://devops.bt.siemens.com/artifactory/api/pypi/pypi-all/simple

stages:
  - check
  - deploy

format:
  stage: check
  script:
    - pip install -i ${PIP_INDEX} black
    - black .
  except:
    - master

style:
  stage: check
  script:
    - pip install -i ${PIP_INDEX} flake8
    - flake8 .
  except:
    - master

pages:
  stage: deploy
  script:
    - pip install -i ${PIP_INDEX} pipenv
    - pipenv install --dev --deploy
    - pipenv run docs
    - cp -r docs/build public
  only:
    - master
  artifacts:
    paths:
      - public
    expire_in: 1 day
