image: $DOCKER_POETRY

variables:
  http_proxy: $CODE_PROXY
  https_proxy: $CODE_PROXY
  no_proxy: $NO_PROXY

stages:
  - check
  - test
  - publish
  - document

format_and_style:
  stage: check
  script:
    - poetry install --no-root
    - poetry run black .
    - poetry run flake8 .
  except:
    - master

testsuite:
  stage: test
  services:
    - name: $DOCKER_FOSSOLOGY
      alias: fossology
  script:
    - poetry install -n
    - poetry run python tests/tests.py
  except:
    - master

package:
  stage: publish
  before_script:
    - mkdir -p ~/.config/pypoetry && touch ~/.config/pypoetry/config.toml
    - poetry config repositories.captain https://captain.rtf.siemens.net/artifactory/api/pypi/siemens-pypi
    - echo Publishing the package as $CAPTAIN_USER
  script:
    - poetry build
    - poetry publish --repository captain --username $CAPTAIN_USER --password $CAPTAIN_PASSWD
  when: manual
  only:
    - tags

pages:
  stage: document
  script:
    - poetry install --no-root -n
    - poetry run sphinx-build docs-source docs/
    - cp -r docs/ public
  only:
    - master
  artifacts:
    paths:
      - public
    expire_in: 1 day
